import { Module } from "@/types";

export const MODULES: Module[] = [
  {
    id: "product-brief",
    slug: "product-brief",
    title: "Product Brief",
    description: "Describe tu producto",
    icon: "Package",
    order: 1,
    status: "pending",
  },
  {
    id: "audience-discovery",
    slug: "audience-discovery",
    title: "Audience Discovery",
    description: "Audiencias ideales",
    icon: "Users",
    order: 2,
    status: "pending",
  },
  {
    id: "keyword-intelligence",
    slug: "keyword-intelligence",
    title: "Keyword Intelligence",
    description: "Keywords por intención",
    icon: "Search",
    order: 3,
    status: "pending",
  },
  {
    id: "ad-generator",
    slug: "ad-generator",
    title: "Ad Generator",
    description: "Copies de anuncios",
    icon: "Megaphone",
    order: 4,
    status: "pending",
  },
  {
    id: "post-generator",
    slug: "post-generator",
    title: "Post Generator",
    description: "Posts para redes sociales",
    icon: "Image",
    order: 5,
    status: "pending",
  },
  {
    id: "content-generator",
    slug: "content-generator",
    title: "Content Generator",
    description: "Artículo de blog",
    icon: "FileText",
    order: 6,
    status: "pending",
  },
  {
    id: "team-briefing",
    slug: "team-briefing",
    title: "Team Briefing",
    description: "Documento para el equipo",
    icon: "Presentation",
    order: 7,
    status: "pending",
  },
];
